# Use the base image
FROM ollama/ollama

# Set the working directory
WORKDIR /root/.ollama

# Copy the necessary files into the container
COPY ./ollama_files /root/.ollama

# Expose the required port
EXPOSE 11434
