services:
  ollama-gemma_2b:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama_gemma_2b
    ports:
      - 11434:11434
    restart: always
    stdin_open: true
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 4GB
    restart: always